version: '3.7'
services:
    redis:
        image: redis:6.0.1
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
    db:
        image: mysql:8.0.2
        restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: testp
            MYSQL_USER: testp
            MYSQL_PASSWORD: testp
            MYSQL_DATABASE: testp
    web:
        build: .
        command: bash -c "python /app/manage.py runserver 0.0.0.0:8000 && python manage.py runjobs daily"
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis