# Generated by Django 3.0.5 on 2020-05-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Ссылка для сжатия', max_length=4048)),
                ('subpart', models.SlugField(help_text='введите желаемую часть ссылки', max_length=5, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
